name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint
        run: |
          flake8 Agile-MLOps-Deployment-Docker-AWS-CI-CD-Pipeline-main --count --select=E9,F63,F7,F82 --show-source --statistics || true
          flake8 Agile-MLOps-Deployment-Docker-AWS-CI-CD-Pipeline-main --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      - name: Tests
        run: |
          pytest -q
